"use strict";
// let a: number;
// let b: boolean;
// let c: string;
// let d: any;
// let e: number[] = [1,2,3];
// let f: any[] = [1, true, 'a', false];
Object.defineProperty(exports, "__esModule", { value: true });
// const ColorRed = 0;
// const ColorGreen = 1;
// const ColorBlue = 2;
// enum Color {Red = 0, Green = 1, Blue = 2 };
// let backgroundColor = Color.Red;
// console.log(backgroundColor);
// let message;
// message = 'abc';
// let endsWithC = (<string>message).endsWith('c');
// let alternativeWay = (message as string).endsWith('c');
// import { Point } from './point';
var like_component_1 = require("./like.component");
// let loint = new Point(1, 2);
// let x = point.x;
// point.x = 10;
// point.draw();
// let matt = new Like(100, false);
// matt.clientClick();
// matt.clientClick();
var component = new like_component_1.LikeComponent(10, true);
component.onClick();
console.log("likesCount: " + component.likesCount + ", isSelected: " + component.isSelected);
